#!/bin/bash
declare -A dirs
declare -A results
dirs["Backups"]=""
dirs["Books"]=""
dirs["Comics"]=""
dirs["Home"]=""
dirs["Movies"]=""
dirs["Music"]=""
dirs["Pictures"]="--exclude thumbnail --exclude .thumbcache --exclude thumbnails-digikam.db --exclude thumbnails-digikam.db-journal --exclude .dtrash"
dirs["pv"]=""
dirs["Roms"]=""
dirs["Stuff"]="--exclude Home/.ignore --exclude Home/.cache --exclude Home/.mozilla"
dirs["Television"]=""
dirs["Virtual"]=""
dirs["Volumes"]="--exclude immich/thumbs --exclude immich/encoded-video"

# shellcheck disable=2154
for MNT in /media/*/*; do
	echo -n "Update ${MNT}? "
	read -r CHECK
	if [ "$CHECK" != "n" ]; then
    for DIR in "${!dirs[@]}"; do
      if [ -n "$1" ] && [ "$1" != "$DIR" ]; then continue;fi
      echo "Updating $DIR with options: ${dirs[$DIR]}"
      ionice -c 3 sudo rsync -av --delete-during ${dirs[$DIR]} "/tank/${DIR}/" "${MNT}/${DIR}/"
      results[$DIR]="$?"
    done
	fi
done
echo Return codes:
for DIR in "${!dirs[@]}"; do
  echo "$DIR ${results[$DIR]}"
done
echo Done
