#!/bin/sh
cd /tank/Downloads/Comics || exit
for F in [DM]*Week*;do mv "$F" "$(echo "$F"|sed -e 's/^\([DM].*\) (\(.*\)-\(.*\)-\(20.*\)).*$/\4-\2-\3-\1/')";done
for F in 2*[MD]*/*.cb[rz];do G=$(echo "$F"|sed -e 's/GetComics.INFO//g' -e 's/([^0-9]*)//g' -e 's/ *\.c/.c/g');mv "$F" "$G";done
