#!/bin/bash
if [ -z "$2" ]
then docker exec -it `docker ps|grep $1|head -1|cut -f1 -d" "` /bin/sh -c "[ -e /bin/bash ] && /bin/bash || /bin/sh"
else docker exec -it `docker ps|grep $1|head -1|cut -f1 -d" "` $2 $3 $4 $5 $6 $7 $8 $9
fi
