#!/bin/bash
SYNC_DIR=~/Sync/Unwatched-Movies
rm -rf "${SYNC_DIR}"
curl -X 'GET' -H 'accept: application/json' -H "Authorization: Mediabrowser Token=\"$JELLYFIN_TOKEN\"" 'https://media.adebenham.com/Users/a518e04f58724d04a36c2e599ce625e2/Items?SortBy=SeriesSortName%2CSortName&SortOrder=Ascending&IncludeItemTypes=Movie&Recursive=true&Fields=PrimaryImageAspectRatio%2CMediaSourceCount&IsMissing=false&ImageTypeLimit=1&EnableImages=false&StartIndex=0&Filters=IsUnPlayed&EnableImages=false&Fields=Path' > /tmp/unwatched.json
for ROW in $( jq -r '.Items[].Path | @base64' < /tmp/unwatched.json )
do DATA=$(echo "$ROW" | base64 --decode)
  FILE="$(echo "$DATA" | sed -e 's/^.*Movies\///g')"
  DIR="$(dirname "$FILE")"
  echo "$FILE"
  mkdir -p "${SYNC_DIR}/${DIR}" 2>/dev/null
  ln -s "/media/cjd/bigdisk/Movies/$FILE" "${SYNC_DIR}/${DIR}" 2>/dev/null
done
