#!/bin/bash
export PATH=~/Sync/bin/$(uname -m):~/Sync/bin:~/Sync/bin/appimage:~/go/bin:~/.local/bin:/usr/local/bin:/usr/bin:/usr/sbin:/sbin:/bin
xmodmap -e 'keycode 135 = Super_R' && xset -r 135
if [ "$XDG_SESSION_TYPE" = "wayland" ];then
  HP=$(wlr-randr|grep DP|grep HP |cut -f1 -d" ")
  ACER=$(wlr-randr|grep DP|grep Acer |cut -f1 -d" ")
  if [ "$1" = "safe" ]; then
    wlr-randr --output eDP-1 --on
    exit
  fi
#  wlr-randr --output eDP-1 --off --output "$HP" --pos 0,0 --output "$ACER" --pos 2560,0
  wlr-randr --output "$HP" --pos 0,0 --output "$ACER" --pos 2560,0
  pkill waycorner
  pkill wl-mirror
  waycorner &
else
  xrandr --auto
  sleep 2
  if [ "$1" = "safe" ]
    then xrandr --output eDP-1 --primary --mode 1920x1200
    exit
  fi
  
  if grep -q closed /proc/acpi/button/lid/LID/state
  then CMD="--output eDP-1 --off"
  else CMD="--output eDP-1 --mode 1920x1200"
    LAST="eDP-1"
    eval "xrandr $CMD"
  fi
  
  export IFS=$'\n'
  DISPLAYNAMES=$(xrandr -q|grep " connec" | cut -f1 -d" " | grep -v eDP-1)
  for DISP in $DISPLAYNAMES
    do if [ -z "$LAST" ]
      then CMD="$CMD --output $DISP --preferred"
      else CMD="$CMD --output $DISP --preferred --right-of $LAST"
    fi
    LAST=$DISP
  done
  CMD="$CMD --primary"
  echo xrandr "$CMD"
  eval "xrandr $CMD"
fi
