#!/usr/bin/bash
PROJ=${1%:*}
TOKEN=${1#*:}
gcloud config configurations create "inspect-${PROJ}"
gcloud config configurations activate "inspect-${PROJ}"
echo -n "$TOKEN" > /tmp/inspection-"${PROJ}"
gcloud config set auth/authorization_token_file "/tmp/inspection-${PROJ}"
gcloud config set core/project "${PROJ}"
gcloud config set billing/quota_project LEGACY
gcloud config set account "${USER}@google.com"
gcloud projects describe "${PROJ}"
$SHELL
gcloud config configurations activate default
gcloud config configurations delete "inspect-${PROJ}"
rm "/tmp/inspection-${PROJ}"
