#!/bin/bash
if [ "$1" = "c3" ]
then shift
    K="c3 $(kubectl get pod -n c3 | grep -E 'Running|Init' | grep "$1" | head -n1)"
else K=$(kubectl get pod -A | grep -v "^c3" | grep -E 'Running|Init' | grep "$1" | head -n1)
fi
shift
IMAGE="$1"
shift
# shellcheck disable=2001
NS=$(echo "$K" | sed -e 's/^\([^ ]*\) .*$/\1/g')
# shellcheck disable=2001
POD=$(echo "$K" | sed -e 's/^[^ ]* *\([^ ]*\) *.*$/\1/g')
CONTAINER=$(kubectl get pods "$POD" -n "$NS" -o jsonpath='{.spec.containers[0].name}')
if [ -z "$1" ]; then
  kubectl debug -it "$POD" -n "$NS" --image="${IMAGE}" --target="$CONTAINER"
else
  kubectl debug -it "$POD" -n "$NS" --image="${IMAGE}" --target="$CONTAINER" -- "$@"
fi
