#!/bin/bash
if [ "$1" = "c3" ]
then shift
    K="c3 `kubectl get pod -n c3 | grep -E 'Running|Init' | grep $1 | head -n1`"
else K=`kubectl get pod -A | grep -v "^c3" | grep -E 'Running|Init|CrashLoopBackOff|Init' | grep $1 | head -n1`
fi
NS=`echo $K | sed -e 's/^\([^ ]*\) .*$/\1/g'`
POD=`echo $K | sed -e 's/^[^ ]* *\([^ ]*\) *.*$/\1/g'`
echo Logging into ${POD} in ${NS} namespace
if [ -z "$2" ]
then kubectl exec -it pod/${POD} -n ${NS} -- /bin/sh -c "[ -e /bin/bash ] && exec /bin/bash || exec /bin/sh"
else if [ "$2" = "-c" ]
        then if [ -z "$4" ]
                then kubectl exec -it pod/${POD} -n ${NS} -c $3 -- /bin/sh -c "[ -e /bin/bash ] && exec /bin/bash || exec /bin/sh"
                else kubectl exec -it pod/${POD} -n ${NS} -c $3 -- $4 $5 $6 $7 $8 $9
                fi
        else kubectl exec -it pod/${POD} -n ${NS} -- $2 $3 $4 $5 $6 $7 $8 $9
        fi
fi
