#!/bin/bash
NS=""
if [ "$1" = "c3" ]
  then NS="c3"
  shift
fi
if [ -z "$2" ]
  then TYPE="statefulset"; NAME=$1
  else TYPE=$1; NAME=$2
fi

if [ -z "$NS" ]
then K=$(kubectl get "$TYPE" -A | grep -v "^c3" | grep "$NAME" | head -n1)
else K="$NS $(kubectl get "$TYPE" -n "$NS" | grep "$NAME" | head -n1)"
fi

# shellcheck disable=SC2001
NS=$(echo "$K" | sed -e 's/^\([^ ]*\) .*$/\1/g')
# shellcheck disable=SC2001
POD=$(echo "$K" | sed -e 's/^[^ ]* *\([^ ]*\) *.*$/\1/g')
echo "Restarting $TYPE ${POD} in ${NS} namespace"
read -p "Run kubectl rollout restart $TYPE $POD -n $NS ? " -n 1 -r
echo
if [ "$REPLY" = "y" ]
  then kubectl rollout restart "$TYPE" "$POD" -n "$NS"
fi
