#!/bin/bash
if [ "$1" = "c3" ]
then shift
    K="c3 $(kubectl get pod -n c3 | grep -E 'Running|Init' | grep "$1" | head -n1)"
else K=$(kubectl get pod -A | grep -v "^c3" | grep -E 'Running|Init' | grep "$1" | head -n1)
fi
# shellcheck disable=2001
NS=$(echo "$K" | sed -e 's/^\([^ ]*\) .*$/\1/g')
# shellcheck disable=2001
POD=$(echo "$K" | sed -e 's/^[^ ]* *\([^ ]*\) *.*$/\1/g')
# NODE=$(kubectl describe pod "$POD" -n "$NS" | grep Node: | sed -e 's/^.* \([a-z].*\)\/.*$/\1/g')
# if [ "$NODE" = "$(hostname)" ]; then
#     PODPID=$(sudo crictl inspect "$(sudo crictl ps |grep "$POD" | awk '{ print $1; }'|head -1)" | grep '"pid": [0-9]*,' |awk '{print $2}' |sed -e 's/,//g')
#     sudo rm -rf "/tmp/kv.$PODPID"
#     mkdir "/tmp/kv.$PODPID"
#     awk '/rw/ {print $2}' /proc/"$PODPID"/mounts|grep -v "^/proc" |grep -v "^/dev" |grep -v "^/var"|grep -v "^/sys"| grep -v "^/run" |while read -r M
#     do sudo ln -s "/proc/$PODPID/root/$M" "/tmp/kv.$PODPID/$(basename "$M")"
#     done
#     ls -l "/tmp/kv.$PODPID"
#     nvim "/tmp/kv.$PODPID"
#     sudo rm -rf "/tmp/kv.$PODPID"
# fi
#
#vim scp://$NODE//k8s/$NS/
CONTAINER=$(kubectl get pods "$POD" -n "$NS" -o jsonpath='{.spec.containers[0].name}')
kubectl debug -it "$POD" -n "$NS" --image=debenham/nvim --target="$CONTAINER"
