#!/bin/sh
#SINK=$(wpctl status|grep "Virtual sink" |grep vol|sed -e 's/^.* \([0-9]*\)\. .*/\1/')
SINK=$(wpctl status|grep "Snowball" |grep vol|sed -e 's/^.* \([0-9]*\)\. .*/\1/')
wpctl set-mute "$SINK" toggle
#obs-cli toggle-mute Mic/Aux
~/Sync/bin/obs-cli scene-item toggle Camera "Mute Overlay"
pkill -SIGRTMIN+10 i3blocks
