#!/bin/sh
if [ -z "`tty`" ]
then gnome-terminal -x $* &
fi

if [ -z "$1" ]
then grep "^elif" $0 | sed -e 's/ -X//g' -e 's/^.*= \(.*\) ].*ssh\(.*\)$/\1: \2/g' -e 's/-p \([0-9]*\) \(.*\)/\2:\1/g'
elif [ $1 = jimbob ]; then ssh -X cjd@192.168.86.2
elif [ $1 = dock ]; then ssh -X cjd@dock.lan
elif [ $1 = nuc ]; then ssh -X cjd@nuc.lan
elif [ $1 = piserve ]; then ssh -X cjd@piserve.lan
elif [ $1 = piserve2 ]; then ssh -X cjd@piserve2.lan
elif [ $1 = adebenham ]; then ssh cjd@adebenham.com
elif [ $1 = fugue ]
  then (python /home/debenham/Nextcloud/Config/.weechat/python/pyrnotify.py 12001 &)
  ssh -C -R 12001:localhost:12001 debenham@fugue.syd.corp.google.com
elif [ $1 = home ]; then ssh -X -p 443 \
-L localhost:1627:localhost:1627 `# Home assistant - gdrive backup` \
-L localhost:1883:localhost:1883 `# MQTT` \
-L localhost:5900:jimbob:5900 -L localhost:5901:jimbob:5901 -L localhost:5902:jimbob:5902 -L localhost:5903:jimbob:5903 -L localhost:5904:jimbob:5904 `# VNC/Spice` \
-L localhost:55414:backup:55414 `# Urbackup` \
$2 $3 $4 $5 cjd@home.adebenham.com
else ssh -X $*
fi
