#!/bin/bash
CLI=${HOME}/Sync/bin/obs-cli
if [ $1 -eq 1 ]
then $CLI switch-scene "Camera Only"
elif [ $1 -eq 2 ]
then $CLI switch-scene "Camera2"
elif [ $1 -eq 3 ]
then $CLI switch-scene "Zoomed"
elif [ $1 -eq 4 ]
then $CLI switch-scene "Camera2 Zoomed"
elif [ $1 -eq 5 ]
then $CLI switch-scene "Camera AFK"
elif [ $1 -eq 6 ]
then $CLI switch-scene "Fake Cam"
elif [ $1 -eq 7 ]
then $CLI switch-scene "Thumbs Up"
elif [ $1 -eq 8 ]
then $CLI switch-scene "Thumbs Down"
fi
echo `date` $1 >> /tmp/obscli
