#!/bin/sh
PATH=~/Sync/bin/x86_64/:$PATH
if [ "$XDG_SESSION_TYPE" = "wayland" ]; then CMD=wofi; else CMD=rofi;fi
TEXT=$( echo "" | $CMD -dmenu -p "Enter Text for OBS" -theme-str 'listview { enabled: false;}')
if [ -z "$TEXT" ];
then obs-cli sceneitem hide Camera "Overlay Text"
else obs-cli sceneitem show Camera "Overlay Text"
fi
obs-cli label text "Overlay Text" "$TEXT"
obs-cli scene switch "Camera"
