#!/usr/bin/bash
PATH=~/Sync/bin:~/Sync/bin/x86_64:${PATH}
cd ~/Sync/OBS/memes || exit
if [ "$XDG_SESSION_TYPE" = "wayland" ]; then
	CMD=wofi
	DM="--dmenu"
else
	CMD=rofi
	DM="-dmenu"
fi
chosen=$( (
	echo "Blank"
	jq '.scene_order[]|.name' ~/.config/obs-studio/basic/scenes/Work.json | sed -e 's/"//g' -e 's/^/🎥 /g'
  ls
) | $CMD $DM -i -no-custom)
[ -z "$chosen" ] && exit
if [[ ${chosen::1} == "🎥" ]]; then
	if [[ ${chosen:2:4} == "Text" ]]; then
		TEXT=$(echo "" | $CMD $DM -p "Enter Text for OBS" -theme-str 'listview { enabled: false;}')
		if [ "$TEXT" ]; then
      convert -size 1280x720 pattern:gray50 -auto-level +level-colors red,blue -pointsize 240 -font 'Google-Sans-Bold' \
        -gravity center -fill black -stroke black -strokewidth 5 -annotate +10+10 "$TEXT" \
         -gravity center -define gradient:vector=0,20,0,140 -fill 'gradient:green-blue' -stroke black -strokewidth 5 -annotate +0+0 "$TEXT" \
        -transparent red ~/Sync/OBS/memes/quickshow.gif
      obs-cli scene switch "Camera"
      sleep 1
			obs-cli scene switch "Image"
		else
			obs-cli scene switch Camera
		fi

	else
		obs-cli scene switch "${chosen:2}"
	fi
	exit
fi
obs-cli scene switch "Camera"
rm ~/Sync/OBS/memes/quickshow.gif 2>/dev/null
ln -s "$chosen" quickshow.gif 2>/dev/null
[ "$chosen" = "Blank" ] && exit
sleep 1
obs-cli scene switch "Image"
