#!/bin/bash
CMD=$1
shift
CHROOT=$1
shift

if [ "$CMD" = "run" ]; then
  mkdir -p "$CHROOT"/{dev,etc,home,tmp,proc,root,var}
 
  # setup device
  mknod "$CHROOT/dev/null" c 1 3
  mknod "$CHROOT/dev/zero" c 1 5
  mknod "$CHROOT/dev/tty"  c 5 0
  mknod "$CHROOT/dev/random" c 1 8
  mknod "$CHROOT/dev/urandom" c 1 9
  chmod 0666 "$CHROOT"/dev/{null,tty,zero}
  chown root:tty "$CHROOT/dev/tty"
  chroot "$CHROOT" "$*"
fi

