#!/bin/bash
pkill wl-mirror
REGION=""
if [ "$1" = "-r" ]; then
	REGION=$(slurp)
else
	POS=$(slurp -p | cut -f1 -d,)
	while read -r WIN; do
		WINX=$(echo "$WIN" | cut -f1 -d,)
		if [ "$WINX" -le "$POS" ]; then
			REGION=$WIN
		fi
	done < <(swaymsg -t get_tree | jq -r '.. | (.nodes? // empty)[] | select(.pid and .visible) | .rect | "\(.x),\(.y) \(.width)x\(.height)"' | sort -n )
fi
OFFSETX=$(swaymsg -t get_outputs|jq '.[] | select(.rect.width>0) | .rect.width' |sed -e 'N;s/\n/+/' | bc -l)
if ! (swaymsg -t get_outputs | grep HEAD); then
	swaymsg create_output
fi
RES=$(echo "$REGION" | awk '{print $2}')
HEADLESS=$(swaymsg -t get_outputs|jq '.[]| .name' | grep HEAD)
swaymsg "output $HEADLESS resolution $RES position $OFFSETX 0"
(wl-mirror -r "$REGION"; swaymsg "output $HEADLESS unplug") &
while ! ( swaymsg -t get_tree | grep -q 'Wayland Output');do sleep 1;done
swaymsg "[title=\"Wayland Output\"]" "move to output $HEADLESS"
swaymsg "[title=\"Wayland Output\"]" fullscreen
