#!/bin/bash
pkill wl-mirror
REGION=""
if [ "$1" = "-r" ]; then
	REGION=$(slurp)
else
	POS=$(slurp -p | cut -f1 -d,)
	while read -r WIN; do
		WINX=$(echo "$WIN" | cut -f1 -d,)
		if [ "$WINX" -le "$POS" ]; then
			REGION=$WIN
		fi
	done < <(swaymsg -t get_tree | jq -r '.. | (.nodes? // empty)[] | select(.pid and .visible) | .rect | "\(.x),\(.y) \(.width)x\(.height)"' | sort)
fi
if ! (swaymsg -t get_outputs | grep HEAD); then
	swaymsg create_output
fi
RES=$(echo "$REGION" | awk '{print $2}')
HP=$(swaymsg -t get_outputs |jq '.[] | select(.serial=="6CM9481CF4") | .name')
ACER=$(swaymsg -t get_outputs |jq '.[] | select(.serial=="TD1SA0023900") | .name ')
HEADLESS=$(swaymsg -t get_outputs|jq '.[]| .name' | grep HEAD)
swaymsg "output $HP position 0 0"
swaymsg "output $ACER position 2560 0"
swaymsg "output $HEADLESS resolution $RES position 4480 0"
(wl-mirror -r "$REGION"; swaymsg output $HEADLESS unplug) &
while ! ( swaymsg -t get_tree | grep -q 'Wayland Output');do sleep 1;done
swaymsg "[title=\"Wayland Output\"]" move to output $HEADLESS
swaymsg "[title=\"Wayland Output\"]" fullscreen
