#!/bin/bash
declare -A gitbin
gitbin["bat"]="sharkdp/bat"
gitbin["btop"]="aristocratos/btop"
gitbin["cmctl"]="cert-manager/cert-manager"
gitbin["delta"]="dandavison/delta"
gitbin["dust"]="bootandy/dust"
gitbin["fx"]="antonmedv/fx"
gitbin["fzf"]="junegunn/fzf"
gitbin["gron"]="tomnomnom/gron"
gitbin["k9s"]="derailed/k9s"
gitbin["lazygit"]="jesseduffield/lazygit"
gitbin["lf"]="gokcehan/lf"
gitbin["lnav"]="tstack/lnav"
gitbin["stern"]="stern/stern"
gitbin["trip"]="fujiapple852/trippy"
gitbin["paclear"]="orangekame3/paclear"
#gitbin["pistol"]="doronbehar/pistol"
#gitbin["chroma"]="alecthomas/chroma"

NC='\033[0m' # No Color
RED='\033[1;31m'
BLUE='\033[1;34m'
GRAY='\033[0;37m'

function grab_bin() {
  SKIPPED=""
  GRABBED=""
	BIN="$1"
	REPO=${gitbin["$BIN"]}
	mkdir -p "$BASE/$REPO"
	cd "$BASE/$REPO" || return
	curl -s -o release "https://api.github.com/repos/${REPO}/releases/latest"
	VERSION=$(grep tag_name release | cut -f4 -d\")
	RELEASED=$(grep published_at release | cut -f4 -d\")
	echo -e "${BLUE}$REPO${NC} $VERSION - $RELEASED"
	for ARCH in x86_64 amd64 arm64 aarch64; do
    CURRENT_VERSION=$(cat "$HOME/Sync/bin/$ARCH/.${BIN}.version" 2>/dev/null)
    if [ "$CURRENT_VERSION" = "$VERSION" ];then
      SKIPPED="$SKIPPED $ARCH"
      continue
    fi
		DOWN=$(grep "download_url" "$BASE/$REPO/release" | grep -i linux | grep $ARCH | grep -v -E "deb|rpm|apk" | sed -e 's/^.*\(https.*\)".*$/\1/g' | head -1)
		if [ -n "$DOWN" ]; then
			cd "$BASE/$REPO" || return
			mkdir $ARCH
			cd $ARCH || exit
			if (echo "$DOWN" | grep -qE "gz$"); then
        (curl -L "$DOWN" | tar xfz -) 2>/dev/null
			elif (echo "$DOWN" | grep -qE "bz2$"); then
        (curl -L "$DOWN" | tar xfj -) 2>/dev/null
			elif (echo "$DOWN" | grep -qE "tbz$"); then
        (curl -L "$DOWN" | tar xfj -) 2>/dev/null
			elif (echo "$DOWN" | grep -qE "zip$"); then
				(curl -L "$DOWN" >a.zip && unzip -q a.zip) 2>/dev/null
			else
        (curl -L -o "$BIN" "$DOWN") 2>/dev/null
        chmod +x "$BIN"
			fi
			FILES=$(find . -type f -name "$BIN" | head -1 | sed -e 's/^.\///g')
			if [ -n "$FILES" ]; then
        echo "$VERSION" > "$HOME/Sync/bin/$ARCH/.${BIN}.version"
				GRABBED="$GRABBED $ARCH"
				if (echo "$DOWN" | grep -qE "arm64|aarch64"); then
					ARCH=aarch64
				else
					ARCH=x86_64
				fi
				mv "$FILES" ~/Sync/bin/$ARCH/
			fi
		fi
	done
  echo -e "Grabbed:${RED}$GRABBED${NC}"
  echo -e "Skipped:${GRAY}$SKIPPED${NC}"
}

BASE=/tmp/gitbin.$$
mkdir $BASE
cd $BASE || exit
if [ -z "$1" ]; then
	for BIN in "${!gitbin[@]}"; do
		grab_bin "$BIN" ""
	done
else
	grab_bin "$1" "$1"
fi
rm -rf $BASE
#chmod +x ~/Sync/bin/*/* 2>/dev/null
