#!/bin/bash
BASE=/tmp/gitbin.$$
mkdir $BASE
cd $BASE || exit
for REPO in sharkdp/bat jesseduffield/lazygit stern/stern derailed/k9s aristocratos/btop dandavision/delta bootandy/dust; do
#for REPO in sharkdp/bat; do
	mkdir -p $BASE/$REPO
	cd $BASE/$REPO || continue
	curl -o release https://api.github.com/repos/${REPO}/releases/latest
	VERSION=$(grep tag_name release | cut -f4 -d:)
	echo "$VERSION"
	for ARCH in x86_64 amd64 arm64 aarch64; do
		DOWN=$(grep "download_url" $BASE/$REPO/release | grep -i linux | grep $ARCH | sed -e 's/^.*\(https.*\)".*$/\1/g' | head -1)
		if [ -n "$DOWN" ]; then
			cd $BASE/$REPO || return
			mkdir $ARCH
			cd $ARCH || exit
			if (echo "$DOWN" | grep -qE "bz$"); then
				(curl -L "$DOWN" | tar xfj -) 2>/dev/null
			else
				(curl -L "$DOWN" | tar xfz -) 2>/dev/null
			fi
			FILES=$(file ./* ./*/* ./*/*/* | awk -F':' '/ELF/ {print $1}')
			if [ -n "$FILES" ]; then
				echo "$FILES"
				if (echo "$DOWN" | grep -qE "arm64|aarch64"); then
					ARCH=aarch64
				else
					ARCH=x86_64
				fi
				mv "$FILES" ~/Sync/bin/$ARCH/
			fi
		fi
	done
	rm -rf $BASE/$REPO
done
rm -rf $BASE
#chmod +x ~/Sync/bin/*/* 2>/dev/null
