#!/bin/sh
for V in "$@"
  do nice -n 19 HandBrakeCLI -Z "H.265 MKV 480p30" --all-subtitles -i "$V" -o "$V.smaller.mkv"
  mv "$V" "$V-orig.mkv"
  mv "$V.smaller.mkv" "$V"
done
for V in "$@"
  do ls -l "$V" "$V-orig.mkv"
done

