#!/bin/sh
pkg=$(/usr/local/android/build-tools/18.0.1/aapt dump badging $1|awk -F" " '/package/ {print $2}'|awk -F"'" '/name=/ {print $2}')
act=$(/usr/local/android/build-tools/18.0.1/aapt dump badging $1|awk -F" " '/launchable-activity/ {print $2}'|awk -F"'" '/name=/ {print $2}')
adb shell am start -n $pkg/$act
