#!/bin/sh
export PATH=$PATH:/home/cjd/.local/bin
if [ -z "$1" ]
then cd /export/Downloads
#sudo chown -Rh cjd.cjd /Downloads/*
#chmod -R a+rX /Downloads/*
tvnamer --config=/home/cjd/Nextcloud/Config/mytvnamerconfig.json -m */*.m* *.m*
else tvnamer --config=/home/cjd/Nextcloud/Config/mytvnamerconfig.json -m "$@"
fi
